export const URL_HOME = "/";
// export const URL_MULTIMEDIA = "/multimedia";
export const URL_PHOTO = "/photo";
export const URL_VIDEO = "/video";
export const URL_AUDIO = "/audio";
export const URL_PROFILE = "/profile";
export const URL_LOGIN = "/login";
export const URL_LOGOUT = "/logout";
export const URL_NOT_FOUND = "/*";
